# Generated by Django 3.1.6 on 2021-04-03 19:02

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='count_dwnd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='title_img',
            field=models.ImageField(blank=True, upload_to=main.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Post_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=main.models.get_upload_path)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='main.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.platform'),
        ),
    ]
