# Generated by Django 3.1.6 on 2021-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210404_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.Category'),
        ),
    ]
