# Generated by Django 3.1.6 on 2021-04-04 18:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210404_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, upload_to=main.models.get_upload_path),
        ),
    ]
