# Generated by Django 3.1.6 on 2021-04-05 13:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_upload_path),
        ),
    ]
