# Generated by Django 3.1.6 on 2021-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_game_oponion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rated_user',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='stars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='oponion',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
