# Generated by Django 3.1.6 on 2021-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210411_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bonus',
            field=models.BooleanField(blank=True, choices=[(True, 'bonus'), (False, 'Just Post')], default=False, null=True),
        ),
    ]
