# Generated by Django 3.1.6 on 2021-04-24 17:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_game_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_upload_path, verbose_name='Video Stream'),
        ),
    ]
