# Generated by Django 3.1.5 on 2021-05-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_category_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_img',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
        ),
    ]
