# Generated by Django 3.1.5 on 2021-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210502_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test'),
        ),
    ]
